##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.1.0] date: [Tue Jun 10 15:47:51 EDT 2025]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = main


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build/main

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/system/init.c \
src/drivers/bbpwm/bbpwm.c \
src/main.c \
src/system/gpio.c \
src/system/tim.c \
src/system/stm32c0xx_it.c \
src/system/stm32c0xx_hal_msp.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_cortex.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_rcc.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_rcc_ex.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_flash.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_flash_ex.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_gpio.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_dma.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_dma_ex.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_pwr.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_pwr_ex.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_exti.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_tim.c \
external/drivers/stm32c0xx/src/stm32c0xx_hal_tim_ex.c \
src/system/system_stm32c0xx.c  

# ASM sources
ASM_SOURCES =  \
src/system/startup_stm32c031xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu


# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
# MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)
MCU = -mcpu=cortex-m0plus

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32C031xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Isrc/system \
-Isrc \
-Iexternal/drivers/stm32c0xx/include \
-Iexternal/drivers/stm32c0xx/include/Legacy \
-Iexternal/drivers/cmsis/include \
-Iexternal/drivers/cmsis/include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = src/system/STM32C031C6Tx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***