##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.1.0] date: [Mon May 26 15:51:20 EDT 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = nucleo_test


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build/nucleo_test

######################################
# source
######################################
# C sources
C_SOURCES =  \
src/system/init.c \
src/drivers/pyro_board/pyro_board_impl.c \
src/drivers/pyro_board/pyro_board.c \
src/drivers/ublox_gnss/ublox_gnss_impl.c \
src/drivers/ublox_gnss/ublox_gnss.c \
src/drivers/ina260/ina260.c \
src/drivers/us_timer/us_timer.c \
src/drivers/bmp581/bmp581.c \
src/drivers/icm45686/icm45686.c \
src/drivers/adis16577/adis16577_impl.c \
src/drivers/adis16577/adis16577.c \
src/drivers/lis3mdl/lis3mdl_impl.c \
src/drivers/lis3mdl/lis3mdl.c \
test/main_test.c \
src/managers/pyro_manager/pyro_manager.c \
src/managers/telemetry_manager/telemetry_manager.c \
src/managers/device_manager/device_manager.c \
src/managers/kalman_manager/kalman_manager.c \
src/services/parameter_statistics_reporting_service/parameter_statistics_reporting_service.c \
src/services/device_action_service/device_action_service.c \
src/services/pyro_service_exampl/pyro_service.c \
src/services/parameter_management_service/parameter_management_service.c \
src/services/event_reporting_service/event_reporting_service.c \
src/services/memory_management_service/memory_management_service.c \
src/services/event_action_service/event_action_service.c \
src/services/time_management_service/time_management_service.c \
src/services/on_board_operations_scheduling_service/on_board_operations_scheduling_service.c \
src/ring_buffer/ring_buffer.c \
src/falafel/falafel.c \
src/low_level/memcpy_s.c \
src/system/gpio.c \
src/system/usart.c \
src/system/usb_otg.c \
src/system/stm32h7xx_it.c \
src/system/stm32h7xx_hal_msp.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_cortex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_rcc.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_rcc_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_flash.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_flash_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_gpio.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_hsem.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_dma.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_dma_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_mdma.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_pwr.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_pwr_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_i2c.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_i2c_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_exti.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_tim.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_tim_ex.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_uart.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_uart_ex.c \
src/system/system_stm32h7xx.c \
src/system/i2c.c \
src/system/spi.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_spi.c \
external/drivers/stm32h7xx/src/stm32h7xx_hal_spi_ex.c \
src/system/tim.c

# ASM sources
ASM_SOURCES =  \
src/system/startup_stm32h723xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H723xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-Isrc/system \
-Isrc \
-Iexternal/drivers/stm32h7xx/include \
-Iexternal/drivers/stm32h7xx/include/Legacy \
-Iexternal/drivers/cmsis/include \
-Iexternal/drivers/cmsis/include \
-Isrc/low_level

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = src/system/STM32H723ZGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir -p $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
